conturs: # разбиение на контуры
  min_points: 30
  contour_points: 50 # const2
  min_diff:       [0.2, 1.2] # const3
  num_of_lenghts: 4 # const4
 
isolated_cluster: # Первые этап - получение изолированных кластеров
  constU1: 0.05
  min_len: 1
  min_dif: [0.2, 1.2]
  divider: 2
  max_div_num: 8

knots: # Для разметки узлов
  min_fuses_num: 15
  stop_const: 1

consts:
  round_const: 2
  const: 0.25
  percent_X: 20
  down_steps: 4
  up_steps: 6
  power_koef: 1.16
  percent_Y: 33
  threshold: 0.8
  Y_step: 2.5